### ISSUE TITLE
Cannot connect to host rubot.pocketfi.org

### ISSUE THREAD

**Issue by tnttol** [vanhbakaa/PocketFi#8]
```
2024-10-28 07:35:54 | ERROR    | 228 - Name | Unknown error: Cannot connect to host rubot.pocketfi.org:443 ssl:False [Connect call failed ('158.160.161.159', 443)]
```

**Comment by tnttol** [comment]
![Screenshot from 2024-10-29 12-54-23](https://github.com/user-attachments/assets/4b0da610-da1c-46a5-8612-a5dcfdf9028e)

now it works fine

**Comment by ivan52605** [comment]
[Архив ZIP - WinRAR.zip](https://github.com/user-attachments/files/17583378/ZIP.-.WinRAR.zip)
вот файл tapper.py с вырезанной функцией если у кого такая же ошибка просто подмените это файл на мой

**Comment by ivan52605** [comment]
Ok

**Comment by ivan52605** [comment]
@vanhbakaa исправили ли вы проблему в коде

**Comment by tnttol** [comment]
> @vanhbakaa исправили ли вы проблему в коде

нет, вернула обратно и закрыла задачу
https://github.com/vanhbakaa/PocketFi/blob/b474610a531f224feba13a17616312c5131551d6/bot/core/tapper.py#L140
